# Generated by Django 5.2.8 on 2025-11-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('detail', models.TextField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('document', models.ImageField(upload_to='doc/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
    ]
