# Generated by Django 5.2.8 on 2025-11-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='higher',
            field=models.CharField(blank=True, choices=[('B.Sc', 'B.Sc'), ('B.A', 'B.A'), ('B.Tech', 'B.Tech'), ('M.Sc', 'M.Sc'), ('M.A', 'M.A'), ('M.Tech', 'M.Tech'), ('MBA', 'MBA'), ('PhD', 'PhD')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(blank=True, choices=[('10th', '10th'), ('12th', '12th'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='doc/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/'),
        ),
    ]
