# Generated by Django 5.2.8 on 2025-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_gender_student_higher_student_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
