# Generated by Django 5.2.8 on 2025-11-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
