# Generated by Django 5.2.8 on 2025-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Eame',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='Query',
            field=models.TextField(null=True),
        ),
    ]
