# Generated by Django 5.2.8 on 2025-12-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_query_eame_alter_query_name_alter_query_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='Eame',
            new_name='Email',
        ),
    ]
